### ISSUE TITLE
Neighbor transpositions (python file missing)

### ISSUE THREAD

**Issue by jerwinkdc** [rajatdiptabiswas/coursera-mathematical-thinking-cs#1]
# Now you should find a sequence of neighbor transpositions of letters that transform the sequence MARINE (letters are numbered 0..5) to the sequence AIRMEN. Transpositions are represented by pairs of integers. For example, the pair (0,1) transforms MARINE to AMRINE. Transpositions are performed from left to right. You should define the sequence as shown:

```
def sequence():

return [(...,...), (...,...),...,(...,...)]
```

(Just replace the dots in the parentheses by pairs of numbers that say which neighbor letters should be replaced. Yes, the format is strange, but this is how python codeblock works...)

**[IT IS MISSING IN THE WEEK 6 FOLDER, I HOPE IT WILL BE UPDATED SOON]
[OTHER SLIDES IN WEEK 6 ARE ALSO MISSING]**

![2020-03-25_070611](https://user-images.githubusercontent.com/57943333/77485081-3cdc9f80-6e67-11ea-9782-1288c2e42504.jpg)
![2020-03-25_070751](https://user-images.githubusercontent.com/57943333/77485159-6990b700-6e67-11ea-8811-4bfca1537a26.jpg)

**Comment by rajatdiptabiswas** [comment]
@jerwinkdc The answer to that particular quiz was trivial and so I did not feel it was necessary to add it to the repo. No worries, I'll add the file nonetheless. 
If possible, try writing the code for it yourself and send me a pull request.

Which slides are you talking about? I just found that single slide in the whole week.
