### ISSUE TITLE
Hey bro,do u have the answers to all questions in this course?

### ISSUE THREAD

**Issue by GerlanW** [rajatdiptabiswas/coursera-mathematical-thinking-cs#2]

**Comment by rajatdiptabiswas** [comment]
Hi @GerlanW 

I'm sorry, I just have these available.
I thought I uploaded all the questions from the course. I'm not exactly sure which other questions you are talking about.
Try looking up other people's repos on the same course. They might have what you are looking for.

Good luck!

**Comment by GerlanW** [comment]
Thx I will check it later.




            
            
                
                    
                            
                                
                            
                            
                                347989530
                            
                    
                        
                            
                                    邮箱：347989530@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 09/18/2020 21:09, Rajat Biswas wrote: 
Hi @GerlanW
I'm sorry, I just have these available.
I thought I uploaded all the questions from the course. I'm not exactly sure which other questions you are talking about.
Try looking up other people's repos on the same course. They might have what you are looking for.
Good luck!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rajatdiptabiswas/coursera-mathematical-thinking-cs/issues/2#issuecomment-694857875",
"url": "https://github.com/rajatdiptabiswas/coursera-mathematical-thinking-cs/issues/2#issuecomment-694857875",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
